# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
     tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: build
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn start
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./luqu.xlsx
        asset_name: luqu
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
